sudo: false
language: java
jdk: oraclejdk7
before_install:
    - mvn clean
install: mvn clean install -DskipTests=true -Dgpg.skip=true
after_success: 
    - codecov
branches:
  only:
    - master